### ISSUE TITLE
Old dependancies

### ISSUE THREAD

**Issue by dannyhrl** [tpeczek/Lib.AspNetCore.ServerSentEvents#47]
I'm looking at using this for our company app, but the Microsoft dependencies are limited to 3.0.0 which we are unable to do because this is too low to work with our other packages. Can you update to allow up to the latest or at least more recent versions of the dependencies?

**Comment by tpeczek** [comment]
Hi @dannyhrl,

I think I need to understand a little bit more about your request.

The NuGet package (https://www.nuget.org/packages/Lib.AspNetCore.ServerSentEvents/8.0.0) is multi-targeting .NET Core 3.1, .NET 5, .NET 6, and .NET Framework 4.6.1+. For .NET Core 3.1, .NET 5, and .NET 6 it has no dependencies. For .NET Framework the dependencies are targeting ASP.NET Core 2.1.X because that's the only version of ASP.NET Core officially supported on .NET Framework.

So which dependencies you would like me to update and what would be the context?

**Comment by dannyhrl** [comment]
Hey @tpeczek, sorry I should have included more information initially - that's what I get for doing it last thing in the work week..

I can certainly give more context! We have a 60+ project solution that (unfortunately) is still running in .NET Framework 4.7.2. When attempting to install your NuGet package I get a warning about `Microsoft.Extensions.DependencyInjection.Abstractions (>= 2.1.0 && < 3.0.0)`
We have another external dependency that requires `Microsoft.Extensions.DependencyInjection.Abstractions >= 3.1.5` so I'm unable to downgrade `Abstractions` 

From my understanding `Microsoft.Extensions.DependencyInjection.Abstractions` currently has `6.0.0` as it's latest that appears to target:

- `.NETCoreApp 6.0`
- `.NETFramework 4.6.1`
- `.NETStandard 2.0`
- `.NETStandard 2.1`

So I guess what I'm asking is: are you able to update your `Microsoft.Extensions.DependencyInjection.Abstractions` to `2.1.0<=3.1.5` (or `3.1.22` to cover all `3.x`) so it is less limiting? I'm not sure if there was any breaking changes between `2.x` and `3.x` though so I can understand if this would not be possible

**Comment by tpeczek** [comment]
Hi @dannyhrl,

Thank you, that makes it clear for me. So it would be about dependencies for .NET Framework which are not ASP.NET Core specific. This makes perfect sense, as they have their own lifetime.

I should be able to make those dependencies without upper bound. There would be of course runtime risk, but if ASP.NET Core is able to work with specific version the library should be as well.
