### ISSUE TITLE
Reconnecting with same ClientId fails

### ISSUE THREAD

**Issue by codetuner** [tpeczek/Lib.AspNetCore.ServerSentEvents#69]
Hi, from what I see in the code of ServerSentEventsMiddleware.cs (lines 82-87 at time of writing): whenever a clientId is found to be already connected, it's connection request will be rejected.
In our case, all devices are controlled and have their known clientId. When a device connects, it gives it's clientId (which is then grabbed by a custom IServerSentEventsClientIdProvider). When the client loses it's connection and reconnects (i.e. page is refreshed) and the server is not yet aware that the old connection is lost, the ServerSentEventsMiddleware will currently reject the new connection in favor of the old broken connection. As a result, the client cannot reconnect anymore until the server knows the old connection is broken.
Wouldn't it be better to throw away the old connection and accept the new connection request ? Or at least support this behavior through options.

**Comment by tpeczek** [comment]
Hi,

I think I agree that this is a bug - if reconnect interval happens to be shorter than connection timeout a client will be prevented from reconnecting which is wrong.

Fixed that will require some thinking because it ultimately leads to a race condition. Somewhere out there is a different thread waiting for a connection to be closed so it can clean up the client instance and part of that flow relies on the client identifier to do so. So it will require some additional state to handle that. I'll have to give it a thought.
